### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by eastmanenator** [mark-hahn/web-browser#43] opened 2015-03-21 00:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [web-browser](https://github.com/mark-hahn/web-browser) package, v1.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'update' of undefined

```
At /home/szymonk/.atom/packages/web-browser/lib/page.coffee:34

TypeError: Cannot read property 'update' of undefined
  at Page.module.exports.Page.update (/home/szymonk/.atom/packages/web-browser/lib/page.coffee:34:23)
  at /home/szymonk/.atom/packages/web-browser/lib/web-browser.coffee:103:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:328:21)
  at WebBrowser.createPage (/home/szymonk/.atom/packages/web-browser/lib/web-browser.coffee:58:38)
  at WebBrowser.setUrlOrCreatePage (/home/szymonk/.atom/packages/web-browser/lib/web-browser.coffee:65:8)
  at HTMLInputElement.<anonymous> (/home/szymonk/.atom/packages/web-browser/lib/omnibox-view.coffee:38:38)
  at HTMLInputElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLInputElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -3:15.0 beautify:beautify-editor (atom-text-editor.editor)
  3x -2:26.2 web-browser:google-it (atom-text-editor.editor)
     -2:00.5 git-history:show-file-history (atom-text-editor.editor)
 21x -1:06.2 beautify:beautify-editor (atom-text-editor.editor)
     -0:50.6 beautify:help-debug-editor (atom-text-editor.editor)
     -0:39.8 application:new-file (atom-text-editor.editor)
     -0:39.4 git-blame:toggle (atom-text-editor.editor)
     -0:38.0 core:paste (atom-text-editor.editor)
     -0:13.9 web-browser:toggle (atom-text-editor.editor)
     -0:09.2 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:08.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:08.2 core:cancel (atom-text-editor.editor.mini)
     -0:07.3 application:new-file (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:06.2 git-blame:toggle (atom-text-editor.editor)
     -0:04.7 web-browser:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "emmet-atom",
      "linter",
      "tabs",
      "tree-view",
      "atom-beautify"
    ]
  },
  "web-browser": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.2.0
bookmarks, v0.35.0
bracket-matcher, v0.73.0
color-picker, v1.5.0
editorconfig, v0.3.3
file-icons, v1.5.1
git-blame, v0.4.0
git-history, v2.3.0
language-json, v0.12.0
language-sass, v0.36.0
language-todo, v0.17.0
minimap, v4.3.1
monokai, v0.12.0
open-last-project, v0.3.5
project-manager, v1.15.5
sublime-tabs, v0.5.1
web-browser, v1.4.2

# Dev
No dev packages
```

**Comment by mark-hahn** [comment] 2015-04-10 22:16
I can't be sure this is fixed because there are no reproduction steps.  But I'll assume it is fixed in 1.4.3.

**Closed by mark-hahn** 2015-04-10 22:16 UTC
