### ISSUE TITLE
Fails to load sites with a self-signed certificate

### ISSUE THREAD

**Issue by dahjelle** [mark-hahn/web-browser#42] opened 2015-03-10 20:11 UTC
Hi!

I'm trying to load a page served on my local machine, but I keep getting a `setURL exception https://localhost:8443` message in the dev console, and a blank page with a loading indicator.

I wonder if this has something to do with having a self-signed certificate on that domain? I get similar behavior on other sites with self-signed certificates.

I'd be completely fine with manually importing certs or some such, but I don't know how to do that either.

Any thoughts?

**Comment by mark-hahn** [comment] 2015-03-11 00:33
> I'd be completely fine with manually importing certs or some such, but I
don't know how to do that either.

I think that you set it up in the desktop chrome browser and the atom one
will use the same settings.  You should test it in the desktop browser
first.  If something doesn't load on the desktop it won't load in Atom
either.  Let me know if this helps.

In any case, there shouldn't be exceptions.  Can you give me an example URL
so I can handle the error better?


On Tue, Mar 10, 2015 at 1:11 PM, David Alan Hjelle <notifications@github.com

**Comment by mark-hahn** [comment] 2015-03-11 00:34
Oh wait.  Are you using a `file://` protocol?  There is a bug in the
`webview` tag that has been fixed but not landed in Atom yet.  This may be
the cause of your problem.

**Comment by dahjelle** [comment] 2015-03-11 13:37
Thanks! Yes, after I imported the certificate (Chrome on OS X uses the built-in Keychain.app for certificates, apparently) it loads fine. I should have thought of that earlier!

As far as the exception, you can see it by going to https://webmail.thehjellejar.com. This page has a certificate->URL mismatch that triggers a `setURL exception https://webmail.thehjellejar.com` exception.

**Comment by mark-hahn** [comment] 2015-05-25 06:22
This web-browser package is no longer supported.  Use the atom package browser-plus instead.

**Closed by mark-hahn** 2015-05-25 06:22 UTC
Labels: bug, help wanted
