### ISSUE TITLE
Crashing every site i tried , atom.io ., google.com , yahoo.com.. nothing works.

### ISSUE THREAD

**Issue by v3ss0n** [mark-hahn/web-browser#46] opened 2015-04-05 09:16 UTC
It crash wherever i go .

**Comment by Aarilight** [comment] 2015-04-05 19:15
This is caused by an incompatibility with the new version of Atom, unfortunately. Hoping it gets fixed soon!

**Comment by mark-hahn** [comment] 2015-04-06 00:34
Ouch.  Will fix this asap. I haven't kept my version up-to-date because my
auto-update never works.

On Sun, Apr 5, 2015 at 12:15 PM, Mackenzie McClane <notifications@github.com

**Comment by v3ss0n** [comment] 2015-04-06 00:38
Thanks a lot. I am using atom-browser-webview now. It works . But same duplicated features on both project. Shouldn't two merged?

**Comment by mark-hahn** [comment] 2015-04-06 00:40
I wanted to merge them and he agreed and then I never heard from him.  He's
also been a bit of a dick.  It's a long story.

**Comment by v3ss0n** [comment] 2015-04-06 23:34
I just realized it was forked from you.

**Comment by mark-hahn** [comment] 2015-04-08 04:41
This is fixed in 1.4.3

**Closed by mark-hahn** 2015-04-08 04:41 UTC

**Comment by v3ss0n** [comment] 2015-04-08 06:46
Thanks , going to test soon.
